MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    USE_INSTANCE : True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
INPUT:
  MIN_SIZE_TRAIN : 600
  MAX_SIZE_TRAIN : 1000
  MIN_SIZE_TEST : 600
  MAX_SIZE_TEST : 1000
DATASETS:
  TRAIN: ("SensingPerson1","SensingPerson2","SensingPerson3","SensingPerson4","SensingPerson5","SensingPerson6","Sensing_coperson_train",)
  TEST: ("SensingPersonTest", "Sensing_coperson_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH : 1
OUTPUT_DIR : "./Sensingpcoco_C4"
